service: sls-sample 

provider: 
  name: aws              
  runtime: python3.6    
  stage: dev             
  region: ap-northeast-1 
  iamRoleStatements: 
    - Effect: Allow
      Action: "apigateway:*"
      Resource: "arn:aws:apigateway:*"
    - Effect: Allow
      Action: "lambda:*"
      Resource: "arn:aws:dynamodb:*"
    - Effect: Allow
      Action: "dynamodb:*"
      Resource: "arn:aws:dynamodb:*"
    - Effect: Allow
      Action: "logs:*"
      Resource: "arn:aws:logs:*"

functions: 
  post:
    handler: handler.handle
    events: 
      - http: 
          path: sls/sample/post
          method: post

resources:
  Resources:
    slssampledb:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: sls_sample_db
